### ISSUE TITLE
Player(二人)の挙動をつくる

### ISSUE THREAD

**Issue by Ayane2003** [HAMU-Studio/Tiltet#39]
基本動作を入れる
・Unityのカプセルで制作する
・左のスティックで移動
・LTでダッシュ
・敵に当たるとノックバック

その他アクションは随時追加する
出来たらDiscordで報告

**Comment by Ayane2003** [comment]
6.25
・ジャンプ
・リスポーン

**Comment by ShunFurusawa** [comment]
ノックバック完成により最初のスポーンシステム以外一通りキャラコン完成しました。ざっくりしか確認してないから企画のほうで確認して何かあれば連絡ください。 @akahori720 @Ayane2003

**Comment by Ayane2003** [comment]
ノックバック時に抵抗しないと、足場外に飛ばされるので抵抗してない時のノックバックで飛ぶ距離は抑えてほしいです。
反対に、ノックバックに抵抗しているとあまり後ろに飛ばないのでこっちはもう少し飛ばされたいです。
また、抵抗時は飛ぶ速度が速いのでノックバックの落下速度をゆっくりにしてもらいたいです。
